/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DonateRouteRouteImport } from './routes/donate/route'
import { Route as Char91_demoChar93RouteRouteImport } from './routes/[_demo]/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LivestreamIndexRouteImport } from './routes/livestream/index'
import { Route as DonateIndexRouteImport } from './routes/donate/index'
import { Route as ProfileDonationsRouteImport } from './routes/profile/donations'
import { Route as DonateSuccessRouteImport } from './routes/donate/success'
import { Route as Char91_demoChar93LivestreamRouteImport } from './routes/[_demo]/livestream'
import { Route as Char91_demoChar93DispenserControlRouteImport } from './routes/[_demo]/dispenser-control'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRouteRoute = DonateRouteRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_demoChar93RouteRoute = Char91_demoChar93RouteRouteImport.update({
  id: '/_demo',
  path: '/_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivestreamIndexRoute = LivestreamIndexRouteImport.update({
  id: '/livestream/',
  path: '/livestream/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonateRouteRoute,
} as any)
const ProfileDonationsRoute = ProfileDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => ProfileRoute,
} as any)
const DonateSuccessRoute = DonateSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DonateRouteRoute,
} as any)
const Char91_demoChar93LivestreamRoute =
  Char91_demoChar93LivestreamRouteImport.update({
    id: '/livestream',
    path: '/livestream',
    getParentRoute: () => Char91_demoChar93RouteRoute,
  } as any)
const Char91_demoChar93DispenserControlRoute =
  Char91_demoChar93DispenserControlRouteImport.update({
    id: '/dispenser-control',
    path: '/dispenser-control',
    getParentRoute: () => Char91_demoChar93RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_demo': typeof Char91_demoChar93RouteRouteWithChildren
  '/donate': typeof DonateRouteRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reports': typeof ReportsRoute
  '/_demo/dispenser-control': typeof Char91_demoChar93DispenserControlRoute
  '/_demo/livestream': typeof Char91_demoChar93LivestreamRoute
  '/donate/success': typeof DonateSuccessRoute
  '/profile/donations': typeof ProfileDonationsRoute
  '/donate/': typeof DonateIndexRoute
  '/livestream/': typeof LivestreamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/_demo': typeof Char91_demoChar93RouteRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reports': typeof ReportsRoute
  '/_demo/dispenser-control': typeof Char91_demoChar93DispenserControlRoute
  '/_demo/livestream': typeof Char91_demoChar93LivestreamRoute
  '/donate/success': typeof DonateSuccessRoute
  '/profile/donations': typeof ProfileDonationsRoute
  '/donate': typeof DonateIndexRoute
  '/livestream': typeof LivestreamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_demo': typeof Char91_demoChar93RouteRouteWithChildren
  '/donate': typeof DonateRouteRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reports': typeof ReportsRoute
  '/_demo/dispenser-control': typeof Char91_demoChar93DispenserControlRoute
  '/_demo/livestream': typeof Char91_demoChar93LivestreamRoute
  '/donate/success': typeof DonateSuccessRoute
  '/profile/donations': typeof ProfileDonationsRoute
  '/donate/': typeof DonateIndexRoute
  '/livestream/': typeof LivestreamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_demo'
    | '/donate'
    | '/profile'
    | '/reports'
    | '/_demo/dispenser-control'
    | '/_demo/livestream'
    | '/donate/success'
    | '/profile/donations'
    | '/donate/'
    | '/livestream/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/_demo'
    | '/profile'
    | '/reports'
    | '/_demo/dispenser-control'
    | '/_demo/livestream'
    | '/donate/success'
    | '/profile/donations'
    | '/donate'
    | '/livestream'
  id:
    | '__root__'
    | '/'
    | '/_demo'
    | '/donate'
    | '/profile'
    | '/reports'
    | '/_demo/dispenser-control'
    | '/_demo/livestream'
    | '/donate/success'
    | '/profile/donations'
    | '/donate/'
    | '/livestream/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91_demoChar93RouteRoute: typeof Char91_demoChar93RouteRouteWithChildren
  DonateRouteRoute: typeof DonateRouteRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  LivestreamIndexRoute: typeof LivestreamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo': {
      id: '/_demo'
      path: '/_demo'
      fullPath: '/_demo'
      preLoaderRoute: typeof Char91_demoChar93RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livestream/': {
      id: '/livestream/'
      path: '/livestream'
      fullPath: '/livestream/'
      preLoaderRoute: typeof LivestreamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/': {
      id: '/donate/'
      path: '/'
      fullPath: '/donate/'
      preLoaderRoute: typeof DonateIndexRouteImport
      parentRoute: typeof DonateRouteRoute
    }
    '/profile/donations': {
      id: '/profile/donations'
      path: '/donations'
      fullPath: '/profile/donations'
      preLoaderRoute: typeof ProfileDonationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/donate/success': {
      id: '/donate/success'
      path: '/success'
      fullPath: '/donate/success'
      preLoaderRoute: typeof DonateSuccessRouteImport
      parentRoute: typeof DonateRouteRoute
    }
    '/_demo/livestream': {
      id: '/_demo/livestream'
      path: '/livestream'
      fullPath: '/_demo/livestream'
      preLoaderRoute: typeof Char91_demoChar93LivestreamRouteImport
      parentRoute: typeof Char91_demoChar93RouteRoute
    }
    '/_demo/dispenser-control': {
      id: '/_demo/dispenser-control'
      path: '/dispenser-control'
      fullPath: '/_demo/dispenser-control'
      preLoaderRoute: typeof Char91_demoChar93DispenserControlRouteImport
      parentRoute: typeof Char91_demoChar93RouteRoute
    }
  }
}

interface Char91_demoChar93RouteRouteChildren {
  Char91_demoChar93DispenserControlRoute: typeof Char91_demoChar93DispenserControlRoute
  Char91_demoChar93LivestreamRoute: typeof Char91_demoChar93LivestreamRoute
}

const Char91_demoChar93RouteRouteChildren: Char91_demoChar93RouteRouteChildren =
  {
    Char91_demoChar93DispenserControlRoute:
      Char91_demoChar93DispenserControlRoute,
    Char91_demoChar93LivestreamRoute: Char91_demoChar93LivestreamRoute,
  }

const Char91_demoChar93RouteRouteWithChildren =
  Char91_demoChar93RouteRoute._addFileChildren(
    Char91_demoChar93RouteRouteChildren,
  )

interface DonateRouteRouteChildren {
  DonateSuccessRoute: typeof DonateSuccessRoute
  DonateIndexRoute: typeof DonateIndexRoute
}

const DonateRouteRouteChildren: DonateRouteRouteChildren = {
  DonateSuccessRoute: DonateSuccessRoute,
  DonateIndexRoute: DonateIndexRoute,
}

const DonateRouteRouteWithChildren = DonateRouteRoute._addFileChildren(
  DonateRouteRouteChildren,
)

interface ProfileRouteChildren {
  ProfileDonationsRoute: typeof ProfileDonationsRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileDonationsRoute: ProfileDonationsRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91_demoChar93RouteRoute: Char91_demoChar93RouteRouteWithChildren,
  DonateRouteRoute: DonateRouteRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ReportsRoute: ReportsRoute,
  LivestreamIndexRoute: LivestreamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
